header: |+
  [![Go Report Card](https://goreportcard.com/badge/github.com/sphireinc/mantis)](https://goreportcard.com/report/github.com/sphireinc/mantis)
  [![Go Reference](https://pkg.go.dev/badge/github.com/sphireinc/mantis.svg)](https://pkg.go.dev/github.com/sphireinc/mantis)

repository:
  url: https://github.com/sphireinc/mantis
  defaultBranch: master
  path: /

includeUnexported: true