name: Create Release

on:
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.18.0-beta1'

      - name: Tidy and Vendor
        run: |
          go mod tidy
          go mod vendor

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.18.0-beta1'

      - name: Tidy and Vendor
        run: |
          go get -u
          go mod tidy
          go mod vendor

      - name: Generate Docs Markdown
        run: |
          go install github.com/princjef/gomarkdoc/cmd/gomarkdoc
          gomarkdoc --output docs/aws.md ./aws
          gomarkdoc --output docs/byte.md ./byte
          gomarkdoc --output docs/cache.md ./cache
          gomarkdoc --output docs/data.md ./data
          gomarkdoc --output docs/database.md ./database
          gomarkdoc --output docs/date.md ./date
          gomarkdoc --output docs/encoding.md ./encoding
          gomarkdoc --output docs/encryption.md ./encryption
          gomarkdoc --output docs/errors.md ./errors
          gomarkdoc --output docs/helper.md ./helper
          gomarkdoc --output docs/http.md ./http
          gomarkdoc --output docs/log.md ./log
          gomarkdoc --output docs/uuid.md ./uuid