on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Generate GoDoc
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Gen GoDoc Script
        run: ./.github/scripts/gen_godoc.sh
        shell: bash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages